name: Create Archive
on:
  push:
    tags:
       - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Conventional changelog generator
      uses: Helmisek/conventional-changelog-generator@v1.0.6-release
      id: changelog
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        current-tag: ${{ steps.get_version.outputs.VERSION }}
        commit-types: 'feat:Features,fix:Bug Fixes'
    - run: |
        echo '${{ steps.changelog.outputs.changelog }}'
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: ${{ steps.get_version.outputs.VERSION }}
        body: ${{ steps.changelog.outputs.changelog }}
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: '${{ steps.get_version.outputs.VERSION }}.zip'
        exclusions: '*.git* .travis.yml'
    - name: Attach vsix to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: '${{ steps.get_version.outputs.VERSION }}.zip'
        asset_name: '${{ steps.get_version.outputs.VERSION }}.zip'
        asset_content_type: application/zip
