name: Create Archive
on:
  push 
  #:
    # tags:
    #    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # - name: Get the version
    #   id: get_version
    #   run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        output-file: "false"
        version-file: 'pom.xml'
        version-path: '<version>'
        skip-version-file: 'true'
    - run: |
        echo '${{ steps.changelog.outputs.tag }} - ${{ steps.changelog.outputs.clean_changelog }}'
    # - name: Create Release
    #   uses: actions/create-release@v1
    #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.changelog.outputs.tag }}
    #     release_name: ${{ steps.changelog.outputs.tag }}
    #     body: ${{ steps.changelog.outputs.clean_changelog }}
    # - name: Archive Release
    #   uses: thedoctor0/zip-release@master
    #   with:
    #     filename: '${{ steps.get_version.outputs.VERSION }}.zip'
    #     exclusions: '*.git* .travis.yml'
    # - name: Attach vsix to release
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: '${{ steps.get_version.outputs.VERSION }}.zip'
    #     asset_name: '${{ steps.get_version.outputs.VERSION }}.zip'
    #     asset_content_type: application/zip
