name: Create Archive
on:
  push:
    tags:
       - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Generate release notes
      id: create_release
      uses: raulanatol/github-actions-releaser@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: '${{ steps.get_version.outputs.VERSION }}.zip'
        exclusions: '*.git* .travis.yml'
    - name: Attach vsix to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: '${{ steps.get_version.outputs.VERSION }}.zip'
        asset_name: '${{ steps.get_version.outputs.VERSION }}.zip'
