name: Create Archive
on:
  push:
    tags:
       - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: "✏️ Generate release changelog"
      id: generate-release-changelog
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        onlyLastTag: "true"
        stripHeaders: "true"
        stripGeneratorNotice: "true"
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: '${{ steps.get_version.outputs.VERSION }}.zip'
        exclusions: '*.git* .travis.yml'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: '${{ steps.get_version.outputs.VERSION }}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{ steps.generate-release-changelog.outputs.changelog }}
